### ISSUE TITLE
[feature request] Reset task

### ISSUE THREAD

**Issue by narimiran** [afractal/PomoTimer#23]
For example, if you have a task called `two hours` which consists of four pomodoro timers of 25min (plus 5min breaks between). When you choose this task, as the time passes its progress goes from 0/4 to 4/4.

It would be nice to have an option to reset the task back to 0/4, so it could be reusable. (For example, every day I want to work on some project for two hours).

**Comment by afractal** [comment]
Thanks for the feature request. 
I will add both this and #24 issue to the **0.2** milestone and start working on them.
